/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ContentBankEntry = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : Time,
  'contentLabel' : IDL.Text,
});
export const Drawing = IDL.Record({
  'id' : IDL.Text,
  'status_external_tl' : IDL.Bool,
  'title' : IDL.Text,
  'scheduledDate' : IDL.Int,
  'status_merch' : IDL.Bool,
  'createdAt' : Time,
  'status_posted' : IDL.Bool,
  'status_bts' : IDL.Bool,
  'status_pov' : IDL.Bool,
  'status_procreate_tl' : IDL.Bool,
  'weekLabel' : IDL.Text,
  'status_edited' : IDL.Bool,
});
export const IdeaVaultCategory = IDL.Variant({
  'merch_idea' : IDL.Null,
  'social_hook' : IDL.Null,
  'lore' : IDL.Null,
  'drawing_idea' : IDL.Null,
});
export const IdeaVaultEntry = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'category' : IdeaVaultCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CatalogEntryInput = IDL.Record({
  'production_cost' : IDL.Float64,
  'linkedProductId' : IDL.Opt(IDL.Text),
  'merch_type' : IDL.Text,
  'size' : IDL.Text,
  'shipping' : IDL.Float64,
  'az_tax_rate' : IDL.Float64,
  'total_cost' : IDL.Float64,
  'item_name' : IDL.Text,
  'quarter_sales' : IDL.Float64,
  'az_tax_total' : IDL.Float64,
  'quarterly_earnings' : IDL.Float64,
  'profit_margin' : IDL.Float64,
  'yearly_sales' : IDL.Float64,
  'yearly_earnings' : IDL.Float64,
  'profit_amount' : IDL.Float64,
});
export const CatalogEntry = IDL.Record({
  'id' : IDL.Text,
  'production_cost' : IDL.Float64,
  'linkedProductId' : IDL.Opt(IDL.Text),
  'merch_type' : IDL.Text,
  'createdAt' : Time,
  'size' : IDL.Text,
  'shipping' : IDL.Float64,
  'az_tax_rate' : IDL.Float64,
  'total_cost' : IDL.Float64,
  'item_name' : IDL.Text,
  'quarter_sales' : IDL.Float64,
  'az_tax_total' : IDL.Float64,
  'quarterly_earnings' : IDL.Float64,
  'profit_margin' : IDL.Float64,
  'yearly_sales' : IDL.Float64,
  'yearly_earnings' : IDL.Float64,
  'profit_amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'shippingAddress' : IDL.Text,
});
export const MerchPipeline = IDL.Record({
  'live' : IDL.Bool,
  'tote' : IDL.Bool,
  'uploaded' : IDL.Bool,
  'magnet' : IDL.Bool,
  'sticker' : IDL.Bool,
  'print' : IDL.Bool,
  'drawingId' : IDL.Text,
  'keychain' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContentBankEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ContentBankEntry],
      [],
    ),
  'addDrawing' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [Drawing], []),
  'addIdeaVaultEntry' : IDL.Func(
      [IdeaVaultCategory, IDL.Text],
      [IdeaVaultEntry],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpsertCatalogEntries' : IDL.Func(
      [IDL.Vec(CatalogEntryInput)],
      [IDL.Vec(CatalogEntry)],
      [],
    ),
  'clearCatalog' : IDL.Func([], [], []),
  'deleteCatalogEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteContentBankEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteDrawing' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteIdeaVaultEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCatalogEntries' : IDL.Func([], [IDL.Vec(CatalogEntry)], ['query']),
  'getContentBank' : IDL.Func([], [IDL.Vec(ContentBankEntry)], ['query']),
  'getDrawings' : IDL.Func([], [IDL.Vec(Drawing)], ['query']),
  'getIdeaVault' : IDL.Func([], [IDL.Vec(IdeaVaultEntry)], ['query']),
  'getMerchPipelines' : IDL.Func([], [IDL.Vec(MerchPipeline)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerOrLogin' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDrawingDate' : IDL.Func([IDL.Text, IDL.Int], [Drawing], []),
  'updateDrawingStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [Drawing],
      [],
    ),
  'upsertMerchPipeline' : IDL.Func(
      [
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
      ],
      [MerchPipeline],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ContentBankEntry = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : Time,
    'contentLabel' : IDL.Text,
  });
  const Drawing = IDL.Record({
    'id' : IDL.Text,
    'status_external_tl' : IDL.Bool,
    'title' : IDL.Text,
    'scheduledDate' : IDL.Int,
    'status_merch' : IDL.Bool,
    'createdAt' : Time,
    'status_posted' : IDL.Bool,
    'status_bts' : IDL.Bool,
    'status_pov' : IDL.Bool,
    'status_procreate_tl' : IDL.Bool,
    'weekLabel' : IDL.Text,
    'status_edited' : IDL.Bool,
  });
  const IdeaVaultCategory = IDL.Variant({
    'merch_idea' : IDL.Null,
    'social_hook' : IDL.Null,
    'lore' : IDL.Null,
    'drawing_idea' : IDL.Null,
  });
  const IdeaVaultEntry = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'category' : IdeaVaultCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CatalogEntryInput = IDL.Record({
    'production_cost' : IDL.Float64,
    'linkedProductId' : IDL.Opt(IDL.Text),
    'merch_type' : IDL.Text,
    'size' : IDL.Text,
    'shipping' : IDL.Float64,
    'az_tax_rate' : IDL.Float64,
    'total_cost' : IDL.Float64,
    'item_name' : IDL.Text,
    'quarter_sales' : IDL.Float64,
    'az_tax_total' : IDL.Float64,
    'quarterly_earnings' : IDL.Float64,
    'profit_margin' : IDL.Float64,
    'yearly_sales' : IDL.Float64,
    'yearly_earnings' : IDL.Float64,
    'profit_amount' : IDL.Float64,
  });
  const CatalogEntry = IDL.Record({
    'id' : IDL.Text,
    'production_cost' : IDL.Float64,
    'linkedProductId' : IDL.Opt(IDL.Text),
    'merch_type' : IDL.Text,
    'createdAt' : Time,
    'size' : IDL.Text,
    'shipping' : IDL.Float64,
    'az_tax_rate' : IDL.Float64,
    'total_cost' : IDL.Float64,
    'item_name' : IDL.Text,
    'quarter_sales' : IDL.Float64,
    'az_tax_total' : IDL.Float64,
    'quarterly_earnings' : IDL.Float64,
    'profit_margin' : IDL.Float64,
    'yearly_sales' : IDL.Float64,
    'yearly_earnings' : IDL.Float64,
    'profit_amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'shippingAddress' : IDL.Text,
  });
  const MerchPipeline = IDL.Record({
    'live' : IDL.Bool,
    'tote' : IDL.Bool,
    'uploaded' : IDL.Bool,
    'magnet' : IDL.Bool,
    'sticker' : IDL.Bool,
    'print' : IDL.Bool,
    'drawingId' : IDL.Text,
    'keychain' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContentBankEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ContentBankEntry],
        [],
      ),
    'addDrawing' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [Drawing], []),
    'addIdeaVaultEntry' : IDL.Func(
        [IdeaVaultCategory, IDL.Text],
        [IdeaVaultEntry],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpsertCatalogEntries' : IDL.Func(
        [IDL.Vec(CatalogEntryInput)],
        [IDL.Vec(CatalogEntry)],
        [],
      ),
    'clearCatalog' : IDL.Func([], [], []),
    'deleteCatalogEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteContentBankEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteDrawing' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteIdeaVaultEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCatalogEntries' : IDL.Func([], [IDL.Vec(CatalogEntry)], ['query']),
    'getContentBank' : IDL.Func([], [IDL.Vec(ContentBankEntry)], ['query']),
    'getDrawings' : IDL.Func([], [IDL.Vec(Drawing)], ['query']),
    'getIdeaVault' : IDL.Func([], [IDL.Vec(IdeaVaultEntry)], ['query']),
    'getMerchPipelines' : IDL.Func([], [IDL.Vec(MerchPipeline)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerOrLogin' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDrawingDate' : IDL.Func([IDL.Text, IDL.Int], [Drawing], []),
    'updateDrawingStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [Drawing],
        [],
      ),
    'upsertMerchPipeline' : IDL.Func(
        [
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
        ],
        [MerchPipeline],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };