/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const CreateProductData = IDL.Record({
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostStatus = IDL.Variant({
  'open' : IDL.Null,
  'answered' : IDL.Null,
});
export const Time = IDL.Int;
export const Reply = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const DiscussionPost = IDL.Record({
  'id' : IDL.Text,
  'status' : PostStatus,
  'question' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'replies' : IDL.Vec(Reply),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'shippingAddress' : IDL.Text,
});
export const Customer = IDL.Principal;
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'recipient' : IDL.Opt(Customer),
  'timestamp' : Time,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'customer' : Customer,
  'date' : Time,
  'items' : IDL.Vec(OrderItem),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const SocialMediaContent = IDL.Record({
  'id' : IDL.Text,
  'media' : IDL.Vec(ExternalBlob),
  'content' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addItemToCart' : IDL.Func([OrderItem], [], []),
  'addProduct' : IDL.Func([CreateProductData, IDL.Vec(ExternalBlob)], [], []),
  'addReply' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Vec(OrderItem)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkout' : IDL.Func([], [IDL.Text], []),
  'clearCart' : IDL.Func([], [], []),
  'createDiscussionPost' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllDiscussionPosts' : IDL.Func([], [IDL.Vec(DiscussionPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getMyMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getMyOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSocialMediaContent' : IDL.Func(
      [],
      [IDL.Vec(SocialMediaContent)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Opt(Customer)], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Text, CreateProductData, IDL.Vec(ExternalBlob)],
      [],
      [],
    ),
  'viewCart' : IDL.Func([], [IDL.Vec(OrderItem)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const CreateProductData = IDL.Record({
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostStatus = IDL.Variant({ 'open' : IDL.Null, 'answered' : IDL.Null });
  const Time = IDL.Int;
  const Reply = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const DiscussionPost = IDL.Record({
    'id' : IDL.Text,
    'status' : PostStatus,
    'question' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'replies' : IDL.Vec(Reply),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'shippingAddress' : IDL.Text,
  });
  const Customer = IDL.Principal;
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'recipient' : IDL.Opt(Customer),
    'timestamp' : Time,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'customer' : Customer,
    'date' : Time,
    'items' : IDL.Vec(OrderItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const SocialMediaContent = IDL.Record({
    'id' : IDL.Text,
    'media' : IDL.Vec(ExternalBlob),
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addItemToCart' : IDL.Func([OrderItem], [], []),
    'addProduct' : IDL.Func([CreateProductData, IDL.Vec(ExternalBlob)], [], []),
    'addReply' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Vec(OrderItem)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkout' : IDL.Func([], [IDL.Text], []),
    'clearCart' : IDL.Func([], [], []),
    'createDiscussionPost' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllDiscussionPosts' : IDL.Func(
        [],
        [IDL.Vec(DiscussionPost)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getMyMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getMyOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSocialMediaContent' : IDL.Func(
        [],
        [IDL.Vec(SocialMediaContent)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Opt(Customer)], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Text, CreateProductData, IDL.Vec(ExternalBlob)],
        [],
        [],
      ),
    'viewCart' : IDL.Func([], [IDL.Vec(OrderItem)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };