/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContentBankEntry {
  'id' : string,
  'url' : string,
  'note' : string,
  'createdAt' : Time,
  'contentLabel' : string,
}
export interface Drawing {
  'id' : string,
  'status_external_tl' : boolean,
  'title' : string,
  'scheduledDate' : bigint,
  'status_merch' : boolean,
  'createdAt' : Time,
  'status_posted' : boolean,
  'status_bts' : boolean,
  'status_pov' : boolean,
  'status_procreate_tl' : boolean,
  'weekLabel' : string,
  'status_edited' : boolean,
}
export type IdeaVaultCategory = { 'merch_idea' : null } |
  { 'social_hook' : null } |
  { 'lore' : null } |
  { 'drawing_idea' : null };
export interface IdeaVaultEntry {
  'id' : string,
  'content' : string,
  'createdAt' : Time,
  'category' : IdeaVaultCategory,
}
export interface MerchPipeline {
  'live' : boolean,
  'tote' : boolean,
  'uploaded' : boolean,
  'magnet' : boolean,
  'sticker' : boolean,
  'print' : boolean,
  'drawingId' : string,
  'keychain' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'shippingAddress' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContentBankEntry' : ActorMethod<
    [string, string, string],
    ContentBankEntry
  >,
  'addDrawing' : ActorMethod<[string, bigint, string], Drawing>,
  'addIdeaVaultEntry' : ActorMethod<
    [IdeaVaultCategory, string],
    IdeaVaultEntry
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteContentBankEntry' : ActorMethod<[string], boolean>,
  'deleteDrawing' : ActorMethod<[string], boolean>,
  'deleteIdeaVaultEntry' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentBank' : ActorMethod<[], Array<ContentBankEntry>>,
  'getDrawings' : ActorMethod<[], Array<Drawing>>,
  'getIdeaVault' : ActorMethod<[], Array<IdeaVaultEntry>>,
  'getMerchPipelines' : ActorMethod<[], Array<MerchPipeline>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerOrLogin' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDrawingDate' : ActorMethod<[string, bigint], Drawing>,
  'updateDrawingStatus' : ActorMethod<[string, string, boolean], Drawing>,
  'upsertMerchPipeline' : ActorMethod<
    [string, boolean, boolean, boolean, boolean, boolean, boolean, boolean],
    MerchPipeline
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];