/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateProductData {
  'inventory' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export type Customer = Principal;
export interface DiscussionPost {
  'id' : string,
  'status' : PostStatus,
  'question' : string,
  'author' : Principal,
  'timestamp' : Time,
  'replies' : Array<Reply>,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : string,
  'content' : string,
  'recipient' : [] | [Customer],
  'timestamp' : Time,
}
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'customer' : Customer,
  'date' : Time,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'productId' : string, 'quantity' : bigint }
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export type PostStatus = { 'open' : null } |
  { 'answered' : null };
export interface Product {
  'id' : string,
  'inventory' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface Reply {
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface SocialMediaContent {
  'id' : string,
  'media' : Array<ExternalBlob>,
  'content' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'shippingAddress' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addItemToCart' : ActorMethod<[OrderItem], undefined>,
  'addProduct' : ActorMethod<
    [CreateProductData, Array<ExternalBlob>],
    undefined
  >,
  'addReply' : ActorMethod<[string, string], undefined>,
  'addToCart' : ActorMethod<[Array<OrderItem>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[], string>,
  'clearCart' : ActorMethod<[], undefined>,
  'createDiscussionPost' : ActorMethod<[string], string>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllDiscussionPosts' : ActorMethod<[], Array<DiscussionPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getMyMessages' : ActorMethod<[], Array<Message>>,
  'getMyOrder' : ActorMethod<[string], [] | [Order]>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSocialMediaContent' : ActorMethod<[], Array<SocialMediaContent>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, [] | [Customer]], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [string, CreateProductData, Array<ExternalBlob>],
    undefined
  >,
  'viewCart' : ActorMethod<[], Array<OrderItem>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];