/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: string;
    sku: string;
    categories: Array<string>;
    shippingPrice: number;
    hasVariants: boolean;
    inventory: bigint;
    name: string;
    description: string;
    variants?: Array<ProductVariant>;
    sizes: Array<string>;
    colors: Array<string>;
    price: bigint;
    taxRate: number;
    images: Array<ExternalBlob>;
}
export interface UserProfile {
    name: string;
    email: string;
    shippingAddress: string;
}
export interface Reply {
    content: string;
    author: Principal;
    timestamp: Time;
}
export type Time = bigint;
export interface SocialMediaContent {
    id: string;
    media: Array<ExternalBlob>;
    content: string;
    timestamp: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface OrderItem {
    productId: string;
    variantId?: string;
    quantity: bigint;
    price: bigint;
}
export interface Comment {
    id: string;
    name: string;
    text: string;
    timestamp: Time;
    parentId: string;
    parentType: CommentParentType;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DiscussionPost {
    id: string;
    status: PostStatus;
    question: string;
    author: Principal;
    timestamp: Time;
    replies: Array<Reply>;
}
export interface ProductVariant {
    id: string;
    inventory: bigint;
    color: string;
    size: string;
    parentProductId: string;
    price: bigint;
}
export interface Order {
    id: string;
    status: OrderStatus;
    total: bigint;
    customer: Customer;
    date: Time;
    items: Array<OrderItem>;
}
export type Customer = Principal;
export interface CreateProductData {
    sku: string;
    categories: Array<string>;
    shippingPrice: number;
    hasVariants: boolean;
    inventory: bigint;
    name: string;
    description: string;
    variants?: Array<ProductVariant>;
    sizes: Array<string>;
    colors: Array<string>;
    price: bigint;
    taxRate: number;
}
export type NotificationType = {
    __kind__: "adminAlert";
    adminAlert: null;
} | {
    __kind__: "orderUpdate";
    orderUpdate: string;
} | {
    __kind__: "lowInventory";
    lowInventory: string;
};
export interface PortfolioItem {
    id: string;
    title: string;
    createdAt: Time;
    description: string;
    category: string;
    image: ExternalBlob;
}
export interface Notification {
    id: string;
    notifType: NotificationType;
    read: boolean;
    recipient: Principal;
    message: string;
    timestamp: Time;
    relatedOrderId?: string;
}
export interface Message {
    id: string;
    content: string;
    recipient?: Customer;
    timestamp: Time;
}
export interface BlogPost {
    id: string;
    title: string;
    createdAt: Time;
    image?: ExternalBlob;
    bodyText: string;
}
export interface GalleryItem {
    id: string;
    title: string;
    createdAt: Time;
    description: string;
    image: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Review {
    reviewText: string;
    productId: string;
    variantId?: string;
    timestamp: Time;
    rating: bigint;
    reviewer: Principal;
    verifiedPurchase: boolean;
}
export enum CommentParentType {
    blogPost = "blogPost",
    galleryItem = "galleryItem"
}
export enum OrderStatus {
    shipped = "shipped",
    pending = "pending",
    delivered = "delivered"
}
export enum PostStatus {
    open = "open",
    answered = "answered"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBlogPost(title: string, bodyText: string, image: ExternalBlob | null): Promise<string>;
    addComment(parentId: string, parentType: CommentParentType, name: string, text: string): Promise<string>;
    addGalleryItem(title: string, description: string, image: ExternalBlob): Promise<string>;
    addItemToCart(item: OrderItem): Promise<void>;
    addPortfolioItem(title: string, description: string, image: ExternalBlob, category: string): Promise<string>;
    addProduct(product: CreateProductData, images: Array<ExternalBlob>): Promise<void>;
    addReply(postId: string, content: string): Promise<void>;
    addToCart(items: Array<OrderItem>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkout(): Promise<string>;
    clearCart(): Promise<void>;
    createDiscussionPost(question: string): Promise<string>;
    deleteProduct(productId: string): Promise<void>;
    getAllDiscussionPosts(): Promise<Array<DiscussionPost>>;
    getAnalyticsData(): Promise<{
        mostClickedProducts: Array<[string, bigint]>;
        mostViewedContent: Array<[string, bigint]>;
        orderCount: bigint;
        totalRevenue: bigint;
        lowInventoryProducts: Array<Product>;
    }>;
    getBlogPosts(): Promise<Array<BlogPost>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommentsByParent(parentId: string, parentType: CommentParentType): Promise<Array<Comment>>;
    getGalleryItems(): Promise<Array<GalleryItem>>;
    getMessages(): Promise<Array<Message>>;
    getMyMessages(): Promise<Array<Message>>;
    getMyOrder(orderId: string): Promise<Order | null>;
    getMyOrders(): Promise<Array<Order>>;
    getOrders(): Promise<Array<Order>>;
    getPortfolioItems(): Promise<Array<PortfolioItem>>;
    getProduct(productId: string): Promise<Product | null>;
    getProductReviews(productId: string): Promise<[Array<Review>, number]>;
    getProductVariants(productId: string): Promise<Array<ProductVariant> | null>;
    getProducts(): Promise<Array<Product>>;
    getSocialMediaContent(): Promise<Array<SocialMediaContent>>;
    getUnreadNotifications(): Promise<Array<Notification>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationAsRead(notificationId: string): Promise<void>;
    recordAnalyticsEvent(eventType: {
        __kind__: "orderComplete";
        orderComplete: null;
    } | {
        __kind__: "contentView";
        contentView: string;
    } | {
        __kind__: "productClick";
        productClick: string;
    }): Promise<void>;
    registerOrLogin(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendAdminBroadcastAlert(message: string): Promise<void>;
    sendMessage(content: string, recipient: Customer | null): Promise<void>;
    submitReview(productId: string, rating: bigint, reviewText: string, variantId: string | null): Promise<void>;
    updateOrderStatus(orderId: string, status: OrderStatus): Promise<void>;
    updateProduct(productId: string, productData: CreateProductData, images: Array<ExternalBlob>): Promise<void>;
    viewCart(): Promise<Array<OrderItem>>;
}
import type { BlogPost as _BlogPost, Comment as _Comment, CommentParentType as _CommentParentType, CreateProductData as _CreateProductData, Customer as _Customer, DiscussionPost as _DiscussionPost, ExternalBlob as _ExternalBlob, GalleryItem as _GalleryItem, Message as _Message, Notification as _Notification, NotificationType as _NotificationType, Order as _Order, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PortfolioItem as _PortfolioItem, PostStatus as _PostStatus, Product as _Product, ProductVariant as _ProductVariant, Reply as _Reply, Review as _Review, SocialMediaContent as _SocialMediaContent, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBlogPost(arg0: string, arg1: string, arg2: ExternalBlob | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(arg0, arg1, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(arg0, arg1, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addComment(arg0: string, arg1: CommentParentType, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, to_candid_CommentParentType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, to_candid_CommentParentType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async addGalleryItem(arg0: string, arg1: string, arg2: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryItem(arg0, arg1, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryItem(arg0, arg1, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addItemToCart(arg0: OrderItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addItemToCart(to_candid_OrderItem_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItemToCart(to_candid_OrderItem_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPortfolioItem(arg0: string, arg1: string, arg2: ExternalBlob, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addPortfolioItem(arg0, arg1, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPortfolioItem(arg0, arg1, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addProduct(arg0: CreateProductData, arg1: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_CreateProductData_n14(this._uploadFile, this._downloadFile, arg0), await to_candid_vec_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_CreateProductData_n14(this._uploadFile, this._downloadFile, arg0), await to_candid_vec_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addReply(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReply(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReply(arg0, arg1);
            return result;
        }
    }
    async addToCart(arg0: Array<OrderItem>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(to_candid_vec_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(to_candid_vec_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkout(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.checkout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkout();
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createDiscussionPost(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDiscussionPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDiscussionPost(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllDiscussionPosts(): Promise<Array<DiscussionPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDiscussionPosts();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDiscussionPosts();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsData(): Promise<{
        mostClickedProducts: Array<[string, bigint]>;
        mostViewedContent: Array<[string, bigint]>;
        orderCount: bigint;
        totalRevenue: bigint;
        lowInventoryProducts: Array<Product>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsData();
                return from_candid_record_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsData();
            return from_candid_record_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommentsByParent(arg0: string, arg1: CommentParentType): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsByParent(arg0, to_candid_CommentParentType_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsByParent(arg0, to_candid_CommentParentType_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryItems();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryItems();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMessages();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMessages();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrder(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrder(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioItems(): Promise<Array<PortfolioItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioItems();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioItems();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductReviews(arg0: string): Promise<[Array<Review>, number]> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductReviews(arg0);
                return [
                    from_candid_vec_n65(this._uploadFile, this._downloadFile, result[0]),
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductReviews(arg0);
            return [
                from_candid_vec_n65(this._uploadFile, this._downloadFile, result[0]),
                result[1]
            ];
        }
    }
    async getProductVariants(arg0: string): Promise<Array<ProductVariant> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductVariants(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductVariants(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSocialMediaContent(): Promise<Array<SocialMediaContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSocialMediaContent();
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSocialMediaContent();
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotifications();
                return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotifications();
            return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async recordAnalyticsEvent(arg0: {
        __kind__: "orderComplete";
        orderComplete: null;
    } | {
        __kind__: "contentView";
        contentView: string;
    } | {
        __kind__: "productClick";
        productClick: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAnalyticsEvent(to_candid_variant_n76(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAnalyticsEvent(to_candid_variant_n76(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async registerOrLogin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOrLogin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOrLogin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendAdminBroadcastAlert(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAdminBroadcastAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAdminBroadcastAlert(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: Customer | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, to_candid_opt_n77(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, to_candid_opt_n77(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitReview(arg0: string, arg1: bigint, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2, to_candid_opt_n78(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2, to_candid_opt_n78(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n79(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n79(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: CreateProductData, arg2: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_CreateProductData_n14(this._uploadFile, this._downloadFile, arg1), await to_candid_vec_n16(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_CreateProductData_n14(this._uploadFile, this._downloadFile, arg1), await to_candid_vec_n16(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async viewCart(): Promise<Array<OrderItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.viewCart();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.viewCart();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_BlogPost_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): Promise<BlogPost> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_CommentParentType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommentParentType): CommentParentType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Comment_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Comment): Comment {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_DiscussionPost_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscussionPost): DiscussionPost {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryItem_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): Promise<GalleryItem> {
    return await from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n73(_uploadFile, _downloadFile, value);
}
function from_candid_OrderItem_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItem): OrderItem {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
async function from_candid_PortfolioItem_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioItem): Promise<PortfolioItem> {
    return await from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_PostStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostStatus): PostStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n67(_uploadFile, _downloadFile, value);
}
async function from_candid_SocialMediaContent_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialMediaContent): Promise<SocialMediaContent> {
    return await from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ProductVariant>]): Array<ProductVariant> | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PostStatus;
    question: string;
    author: Principal;
    timestamp: _Time;
    replies: Array<_Reply>;
}): {
    id: string;
    status: PostStatus;
    question: string;
    author: Principal;
    timestamp: Time;
    replies: Array<Reply>;
} {
    return {
        id: value.id,
        status: from_candid_PostStatus_n23(_uploadFile, _downloadFile, value.status),
        question: value.question,
        author: value.author,
        timestamp: value.timestamp,
        replies: value.replies
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mostClickedProducts: Array<[string, bigint]>;
    mostViewedContent: Array<[string, bigint]>;
    orderCount: bigint;
    totalRevenue: bigint;
    lowInventoryProducts: Array<_Product>;
}): Promise<{
    mostClickedProducts: Array<[string, bigint]>;
    mostViewedContent: Array<[string, bigint]>;
    orderCount: bigint;
    totalRevenue: bigint;
    lowInventoryProducts: Array<Product>;
}> {
    return {
        mostClickedProducts: value.mostClickedProducts,
        mostViewedContent: value.mostViewedContent,
        orderCount: value.orderCount,
        totalRevenue: value.totalRevenue,
        lowInventoryProducts: await from_candid_vec_n26(_uploadFile, _downloadFile, value.lowInventoryProducts)
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    sku: string;
    categories: Array<string>;
    shippingPrice: number;
    hasVariants: boolean;
    inventory: bigint;
    name: string;
    description: string;
    variants: [] | [Array<_ProductVariant>];
    sizes: Array<string>;
    colors: Array<string>;
    price: bigint;
    taxRate: number;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    sku: string;
    categories: Array<string>;
    shippingPrice: number;
    hasVariants: boolean;
    inventory: bigint;
    name: string;
    description: string;
    variants?: Array<ProductVariant>;
    sizes: Array<string>;
    colors: Array<string>;
    price: bigint;
    taxRate: number;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        sku: value.sku,
        categories: value.categories,
        shippingPrice: value.shippingPrice,
        hasVariants: value.hasVariants,
        inventory: value.inventory,
        name: value.name,
        description: value.description,
        variants: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.variants)),
        sizes: value.sizes,
        colors: value.colors,
        price: value.price,
        taxRate: value.taxRate,
        images: await from_candid_vec_n30(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    createdAt: _Time;
    image: [] | [_ExternalBlob];
    bodyText: string;
}): Promise<{
    id: string;
    title: string;
    createdAt: Time;
    image?: ExternalBlob;
    bodyText: string;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        image: record_opt_to_undefined(await from_candid_opt_n35(_uploadFile, _downloadFile, value.image)),
        bodyText: value.bodyText
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    text: string;
    timestamp: _Time;
    parentId: string;
    parentType: _CommentParentType;
}): {
    id: string;
    name: string;
    text: string;
    timestamp: Time;
    parentId: string;
    parentType: CommentParentType;
} {
    return {
        id: value.id,
        name: value.name,
        text: value.text,
        timestamp: value.timestamp,
        parentId: value.parentId,
        parentType: from_candid_CommentParentType_n42(_uploadFile, _downloadFile, value.parentType)
    };
}
async function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    createdAt: _Time;
    description: string;
    image: _ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    createdAt: Time;
    description: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        image: await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.image)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    recipient: [] | [_Customer];
    timestamp: _Time;
}): {
    id: string;
    content: string;
    recipient?: Customer;
    timestamp: Time;
} {
    return {
        id: value.id,
        content: value.content,
        recipient: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.recipient)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    total: bigint;
    customer: _Customer;
    date: _Time;
    items: Array<_OrderItem>;
}): {
    id: string;
    status: OrderStatus;
    total: bigint;
    customer: Customer;
    date: Time;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n54(_uploadFile, _downloadFile, value.status),
        total: value.total,
        customer: value.customer,
        date: value.date,
        items: from_candid_vec_n56(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productId: string;
    variantId: [] | [string];
    quantity: bigint;
    price: bigint;
}): {
    productId: string;
    variantId?: string;
    quantity: bigint;
    price: bigint;
} {
    return {
        productId: value.productId,
        variantId: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.variantId)),
        quantity: value.quantity,
        price: value.price
    };
}
async function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    createdAt: _Time;
    description: string;
    category: string;
    image: _ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    createdAt: Time;
    description: string;
    category: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        category: value.category,
        image: await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.image)
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reviewText: string;
    productId: string;
    variantId: [] | [string];
    timestamp: _Time;
    rating: bigint;
    reviewer: Principal;
    verifiedPurchase: boolean;
}): {
    reviewText: string;
    productId: string;
    variantId?: string;
    timestamp: Time;
    rating: bigint;
    reviewer: Principal;
    verifiedPurchase: boolean;
} {
    return {
        reviewText: value.reviewText,
        productId: value.productId,
        variantId: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.variantId)),
        timestamp: value.timestamp,
        rating: value.rating,
        reviewer: value.reviewer,
        verifiedPurchase: value.verifiedPurchase
    };
}
async function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: Array<_ExternalBlob>;
    content: string;
    timestamp: _Time;
}): Promise<{
    id: string;
    media: Array<ExternalBlob>;
    content: string;
    timestamp: Time;
}> {
    return {
        id: value.id,
        media: await from_candid_vec_n30(_uploadFile, _downloadFile, value.media),
        content: value.content,
        timestamp: value.timestamp
    };
}
function from_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    notifType: _NotificationType;
    read: boolean;
    recipient: Principal;
    message: string;
    timestamp: _Time;
    relatedOrderId: [] | [string];
}): {
    id: string;
    notifType: NotificationType;
    read: boolean;
    recipient: Principal;
    message: string;
    timestamp: Time;
    relatedOrderId?: string;
} {
    return {
        id: value.id,
        notifType: from_candid_NotificationType_n74(_uploadFile, _downloadFile, value.notifType),
        read: value.read,
        recipient: value.recipient,
        message: value.message,
        timestamp: value.timestamp,
        relatedOrderId: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.relatedOrderId))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    open: null;
} | {
    answered: null;
}): PostStatus {
    return "open" in value ? PostStatus.open : "answered" in value ? PostStatus.answered : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blogPost: null;
} | {
    galleryItem: null;
}): CommentParentType {
    return "blogPost" in value ? CommentParentType.blogPost : "galleryItem" in value ? CommentParentType.galleryItem : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : value;
}
function from_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adminAlert: null;
} | {
    orderUpdate: string;
} | {
    lowInventory: string;
}): {
    __kind__: "adminAlert";
    adminAlert: null;
} | {
    __kind__: "orderUpdate";
    orderUpdate: string;
} | {
    __kind__: "lowInventory";
    lowInventory: string;
} {
    return "adminAlert" in value ? {
        __kind__: "adminAlert",
        adminAlert: value.adminAlert
    } : "orderUpdate" in value ? {
        __kind__: "orderUpdate",
        orderUpdate: value.orderUpdate
    } : "lowInventory" in value ? {
        __kind__: "lowInventory",
        lowInventory: value.lowInventory
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiscussionPost>): Array<DiscussionPost> {
    return value.map((x)=>from_candid_DiscussionPost_n21(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Promise<Array<BlogPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BlogPost_n33(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Comment>): Array<Comment> {
    return value.map((x)=>from_candid_Comment_n40(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Promise<Array<GalleryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryItem_n45(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderItem>): Array<OrderItem> {
    return value.map((x)=>from_candid_OrderItem_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n52(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PortfolioItem>): Promise<Array<PortfolioItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PortfolioItem_n62(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n66(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SocialMediaContent>): Promise<Array<SocialMediaContent>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SocialMediaContent_n69(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n72(_uploadFile, _downloadFile, x));
}
function to_candid_CommentParentType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommentParentType): _CommentParentType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProductData_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProductData): _CreateProductData {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_OrderItem_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderItem): _OrderItem {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Customer | null): [] | [_Customer] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productId: string;
    variantId?: string;
    quantity: bigint;
    price: bigint;
}): {
    productId: string;
    variantId: [] | [string];
    quantity: bigint;
    price: bigint;
} {
    return {
        productId: value.productId,
        variantId: value.variantId ? candid_some(value.variantId) : candid_none(),
        quantity: value.quantity,
        price: value.price
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sku: string;
    categories: Array<string>;
    shippingPrice: number;
    hasVariants: boolean;
    inventory: bigint;
    name: string;
    description: string;
    variants?: Array<ProductVariant>;
    sizes: Array<string>;
    colors: Array<string>;
    price: bigint;
    taxRate: number;
}): {
    sku: string;
    categories: Array<string>;
    shippingPrice: number;
    hasVariants: boolean;
    inventory: bigint;
    name: string;
    description: string;
    variants: [] | [Array<_ProductVariant>];
    sizes: Array<string>;
    colors: Array<string>;
    price: bigint;
    taxRate: number;
} {
    return {
        sku: value.sku,
        categories: value.categories,
        shippingPrice: value.shippingPrice,
        hasVariants: value.hasVariants,
        inventory: value.inventory,
        name: value.name,
        description: value.description,
        variants: value.variants ? candid_some(value.variants) : candid_none(),
        sizes: value.sizes,
        colors: value.colors,
        price: value.price,
        taxRate: value.taxRate
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommentParentType): {
    blogPost: null;
} | {
    galleryItem: null;
} {
    return value == CommentParentType.blogPost ? {
        blogPost: null
    } : value == CommentParentType.galleryItem ? {
        galleryItem: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "orderComplete";
    orderComplete: null;
} | {
    __kind__: "contentView";
    contentView: string;
} | {
    __kind__: "productClick";
    productClick: string;
}): {
    orderComplete: null;
} | {
    contentView: string;
} | {
    productClick: string;
} {
    return value.__kind__ === "orderComplete" ? {
        orderComplete: value.orderComplete
    } : value.__kind__ === "contentView" ? {
        contentView: value.contentView
    } : value.__kind__ === "productClick" ? {
        productClick: value.productClick
    } : value;
}
function to_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value;
}
async function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, x)));
}
function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrderItem>): Array<_OrderItem> {
    return value.map((x)=>to_candid_OrderItem_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
