/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Drawing {
    id: string;
    status_external_tl: boolean;
    title: string;
    scheduledDate: bigint;
    status_merch: boolean;
    createdAt: Time;
    status_posted: boolean;
    status_bts: boolean;
    status_pov: boolean;
    status_procreate_tl: boolean;
    weekLabel: string;
    status_edited: boolean;
}
export interface ContentBankEntry {
    id: string;
    url: string;
    note: string;
    createdAt: Time;
    contentLabel: string;
}
export type Time = bigint;
export interface IdeaVaultEntry {
    id: string;
    content: string;
    createdAt: Time;
    category: IdeaVaultCategory;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CatalogEntryInput {
    production_cost: number;
    linkedProductId?: string;
    merch_type: string;
    size: string;
    shipping: number;
    az_tax_rate: number;
    total_cost: number;
    item_name: string;
    quarter_sales: number;
    az_tax_total: number;
    quarterly_earnings: number;
    profit_margin: number;
    yearly_sales: number;
    yearly_earnings: number;
    profit_amount: number;
}
export interface CatalogEntry {
    id: string;
    production_cost: number;
    linkedProductId?: string;
    merch_type: string;
    createdAt: Time;
    size: string;
    shipping: number;
    az_tax_rate: number;
    total_cost: number;
    item_name: string;
    quarter_sales: number;
    az_tax_total: number;
    quarterly_earnings: number;
    profit_margin: number;
    yearly_sales: number;
    yearly_earnings: number;
    profit_amount: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
    email: string;
    shippingAddress: string;
}
export interface MerchPipeline {
    live: boolean;
    tote: boolean;
    uploaded: boolean;
    magnet: boolean;
    sticker: boolean;
    print: boolean;
    drawingId: string;
    keychain: boolean;
}
export enum IdeaVaultCategory {
    merch_idea = "merch_idea",
    social_hook = "social_hook",
    lore = "lore",
    drawing_idea = "drawing_idea"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addContentBankEntry(url: string, contentLabel: string, note: string): Promise<ContentBankEntry>;
    addDrawing(title: string, scheduledDate: bigint, weekLabel: string): Promise<Drawing>;
    addIdeaVaultEntry(category: IdeaVaultCategory, content: string): Promise<IdeaVaultEntry>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkUpsertCatalogEntries(entries: Array<CatalogEntryInput>): Promise<Array<CatalogEntry>>;
    clearCatalog(): Promise<void>;
    deleteCatalogEntry(id: string): Promise<boolean>;
    deleteContentBankEntry(id: string): Promise<boolean>;
    deleteDrawing(id: string): Promise<boolean>;
    deleteIdeaVaultEntry(id: string): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCatalogEntries(): Promise<Array<CatalogEntry>>;
    getContentBank(): Promise<Array<ContentBankEntry>>;
    getDrawings(): Promise<Array<Drawing>>;
    getIdeaVault(): Promise<Array<IdeaVaultEntry>>;
    getMerchPipelines(): Promise<Array<MerchPipeline>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerOrLogin(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateDrawingDate(id: string, newDate: bigint): Promise<Drawing>;
    updateDrawingStatus(id: string, field: string, value: boolean): Promise<Drawing>;
    upsertMerchPipeline(drawingId: string, sticker: boolean, magnet: boolean, keychain: boolean, tote: boolean, print: boolean, uploaded: boolean, live: boolean): Promise<MerchPipeline>;
}
import type { CatalogEntry as _CatalogEntry, CatalogEntryInput as _CatalogEntryInput, IdeaVaultCategory as _IdeaVaultCategory, IdeaVaultEntry as _IdeaVaultEntry, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addContentBankEntry(arg0: string, arg1: string, arg2: string): Promise<ContentBankEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addContentBankEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContentBankEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async addDrawing(arg0: string, arg1: bigint, arg2: string): Promise<Drawing> {
        if (this.processError) {
            try {
                const result = await this.actor.addDrawing(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDrawing(arg0, arg1, arg2);
            return result;
        }
    }
    async addIdeaVaultEntry(arg0: IdeaVaultCategory, arg1: string): Promise<IdeaVaultEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addIdeaVaultEntry(to_candid_IdeaVaultCategory_n8(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_IdeaVaultEntry_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIdeaVaultEntry(to_candid_IdeaVaultCategory_n8(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_IdeaVaultEntry_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkUpsertCatalogEntries(arg0: Array<CatalogEntryInput>): Promise<Array<CatalogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpsertCatalogEntries(to_candid_vec_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpsertCatalogEntries(to_candid_vec_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearCatalog(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCatalog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCatalog();
            return result;
        }
    }
    async deleteCatalogEntry(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCatalogEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCatalogEntry(arg0);
            return result;
        }
    }
    async deleteContentBankEntry(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContentBankEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContentBankEntry(arg0);
            return result;
        }
    }
    async deleteDrawing(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDrawing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDrawing(arg0);
            return result;
        }
    }
    async deleteIdeaVaultEntry(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIdeaVaultEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIdeaVaultEntry(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCatalogEntries(): Promise<Array<CatalogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCatalogEntries();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCatalogEntries();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentBank(): Promise<Array<ContentBankEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentBank();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentBank();
            return result;
        }
    }
    async getDrawings(): Promise<Array<Drawing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrawings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrawings();
            return result;
        }
    }
    async getIdeaVault(): Promise<Array<IdeaVaultEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdeaVault();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdeaVault();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMerchPipelines(): Promise<Array<MerchPipeline>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMerchPipelines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMerchPipelines();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerOrLogin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOrLogin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOrLogin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateDrawingDate(arg0: string, arg1: bigint): Promise<Drawing> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDrawingDate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDrawingDate(arg0, arg1);
            return result;
        }
    }
    async updateDrawingStatus(arg0: string, arg1: string, arg2: boolean): Promise<Drawing> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDrawingStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDrawingStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async upsertMerchPipeline(arg0: string, arg1: boolean, arg2: boolean, arg3: boolean, arg4: boolean, arg5: boolean, arg6: boolean, arg7: boolean): Promise<MerchPipeline> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertMerchPipeline(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertMerchPipeline(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
}
function from_candid_CatalogEntry_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CatalogEntry): CatalogEntry {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_IdeaVaultCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IdeaVaultCategory): IdeaVaultCategory {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_IdeaVaultEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IdeaVaultEntry): IdeaVaultEntry {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    createdAt: _Time;
    category: _IdeaVaultCategory;
}): {
    id: string;
    content: string;
    createdAt: Time;
    category: IdeaVaultCategory;
} {
    return {
        id: value.id,
        content: value.content,
        createdAt: value.createdAt,
        category: from_candid_IdeaVaultCategory_n12(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    production_cost: number;
    linkedProductId: [] | [string];
    merch_type: string;
    createdAt: _Time;
    size: string;
    shipping: number;
    az_tax_rate: number;
    total_cost: number;
    item_name: string;
    quarter_sales: number;
    az_tax_total: number;
    quarterly_earnings: number;
    profit_margin: number;
    yearly_sales: number;
    yearly_earnings: number;
    profit_amount: number;
}): {
    id: string;
    production_cost: number;
    linkedProductId?: string;
    merch_type: string;
    createdAt: Time;
    size: string;
    shipping: number;
    az_tax_rate: number;
    total_cost: number;
    item_name: string;
    quarter_sales: number;
    az_tax_total: number;
    quarterly_earnings: number;
    profit_margin: number;
    yearly_sales: number;
    yearly_earnings: number;
    profit_amount: number;
} {
    return {
        id: value.id,
        production_cost: value.production_cost,
        linkedProductId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.linkedProductId)),
        merch_type: value.merch_type,
        createdAt: value.createdAt,
        size: value.size,
        shipping: value.shipping,
        az_tax_rate: value.az_tax_rate,
        total_cost: value.total_cost,
        item_name: value.item_name,
        quarter_sales: value.quarter_sales,
        az_tax_total: value.az_tax_total,
        quarterly_earnings: value.quarterly_earnings,
        profit_margin: value.profit_margin,
        yearly_sales: value.yearly_sales,
        yearly_earnings: value.yearly_earnings,
        profit_amount: value.profit_amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    merch_idea: null;
} | {
    social_hook: null;
} | {
    lore: null;
} | {
    drawing_idea: null;
}): IdeaVaultCategory {
    return "merch_idea" in value ? IdeaVaultCategory.merch_idea : "social_hook" in value ? IdeaVaultCategory.social_hook : "lore" in value ? IdeaVaultCategory.lore : "drawing_idea" in value ? IdeaVaultCategory.drawing_idea : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CatalogEntry>): Array<CatalogEntry> {
    return value.map((x)=>from_candid_CatalogEntry_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IdeaVaultEntry>): Array<IdeaVaultEntry> {
    return value.map((x)=>from_candid_IdeaVaultEntry_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CatalogEntryInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CatalogEntryInput): _CatalogEntryInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_IdeaVaultCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IdeaVaultCategory): _IdeaVaultCategory {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    production_cost: number;
    linkedProductId?: string;
    merch_type: string;
    size: string;
    shipping: number;
    az_tax_rate: number;
    total_cost: number;
    item_name: string;
    quarter_sales: number;
    az_tax_total: number;
    quarterly_earnings: number;
    profit_margin: number;
    yearly_sales: number;
    yearly_earnings: number;
    profit_amount: number;
}): {
    production_cost: number;
    linkedProductId: [] | [string];
    merch_type: string;
    size: string;
    shipping: number;
    az_tax_rate: number;
    total_cost: number;
    item_name: string;
    quarter_sales: number;
    az_tax_total: number;
    quarterly_earnings: number;
    profit_margin: number;
    yearly_sales: number;
    yearly_earnings: number;
    profit_amount: number;
} {
    return {
        production_cost: value.production_cost,
        linkedProductId: value.linkedProductId ? candid_some(value.linkedProductId) : candid_none(),
        merch_type: value.merch_type,
        size: value.size,
        shipping: value.shipping,
        az_tax_rate: value.az_tax_rate,
        total_cost: value.total_cost,
        item_name: value.item_name,
        quarter_sales: value.quarter_sales,
        az_tax_total: value.az_tax_total,
        quarterly_earnings: value.quarterly_earnings,
        profit_margin: value.profit_margin,
        yearly_sales: value.yearly_sales,
        yearly_earnings: value.yearly_earnings,
        profit_amount: value.profit_amount
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IdeaVaultCategory): {
    merch_idea: null;
} | {
    social_hook: null;
} | {
    lore: null;
} | {
    drawing_idea: null;
} {
    return value == IdeaVaultCategory.merch_idea ? {
        merch_idea: null
    } : value == IdeaVaultCategory.social_hook ? {
        social_hook: null
    } : value == IdeaVaultCategory.lore ? {
        lore: null
    } : value == IdeaVaultCategory.drawing_idea ? {
        drawing_idea: null
    } : value;
}
function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CatalogEntryInput>): Array<_CatalogEntryInput> {
    return value.map((x)=>to_candid_CatalogEntryInput_n17(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
